server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://192.168.137.138:3306/db?useSSL=false
    username: root
    password: wodediannao
    driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
    host: 192.168.137.138
    port: 5672
    username: root
    password: wodediannao
    virtual-host: /
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo